//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLecteur.ServiceReferenceLecteur {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsLecteur", Namespace="http://schemas.datacontract.org/2004/07/wcflibrary")]
    [System.SerializableAttribute()]
    public partial class clsLecteur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string biblioPrincipaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string biblioPrincipale {
            get {
                return this.biblioPrincipaleField;
            }
            set {
                if ((object.ReferenceEquals(this.biblioPrincipaleField, value) != true)) {
                    this.biblioPrincipaleField = value;
                    this.RaisePropertyChanged("biblioPrincipale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLecteur.IServiceLecteur")]
    public interface IServiceLecteur {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/getAll", ReplyAction="http://tempuri.org/IServiceLecteur/getAllResponse")]
        BiblioLecteur.ServiceReferenceLecteur.clsLecteur[] getAll(string user, string pass, string biblio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLecteur/getAll", ReplyAction="http://tempuri.org/IServiceLecteur/getAllResponse")]
        System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceLecteur.clsLecteur[]> getAllAsync(string user, string pass, string biblio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLecteurChannel : BiblioLecteur.ServiceReferenceLecteur.IServiceLecteur, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLecteurClient : System.ServiceModel.ClientBase<BiblioLecteur.ServiceReferenceLecteur.IServiceLecteur>, BiblioLecteur.ServiceReferenceLecteur.IServiceLecteur {
        
        public ServiceLecteurClient() {
        }
        
        public ServiceLecteurClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLecteurClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLecteurClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLecteurClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BiblioLecteur.ServiceReferenceLecteur.clsLecteur[] getAll(string user, string pass, string biblio) {
            return base.Channel.getAll(user, pass, biblio);
        }
        
        public System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceLecteur.clsLecteur[]> getAllAsync(string user, string pass, string biblio) {
            return base.Channel.getAllAsync(user, pass, biblio);
        }
    }
}
