//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLecteur.ServiceReferenceBiblio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsBiblio", Namespace="http://schemas.datacontract.org/2004/07/wcflibrary")]
    [System.SerializableAttribute()]
    public partial class clsBiblio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string libelléField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string libellé {
            get {
                return this.libelléField;
            }
            set {
                if ((object.ReferenceEquals(this.libelléField, value) != true)) {
                    this.libelléField = value;
                    this.RaisePropertyChanged("libellé");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBiblio.IServiceBiblio")]
    public interface IServiceBiblio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblio/Select_BiblioPrincipale", ReplyAction="http://tempuri.org/IServiceBiblio/Select_BiblioPrincipaleResponse")]
        BiblioLecteur.ServiceReferenceBiblio.clsBiblio[] Select_BiblioPrincipale(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblio/Select_BiblioPrincipale", ReplyAction="http://tempuri.org/IServiceBiblio/Select_BiblioPrincipaleResponse")]
        System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceBiblio.clsBiblio[]> Select_BiblioPrincipaleAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblio/Select_BiblioPrincipaleAdo", ReplyAction="http://tempuri.org/IServiceBiblio/Select_BiblioPrincipaleAdoResponse")]
        string Select_BiblioPrincipaleAdo(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblio/Select_BiblioPrincipaleAdo", ReplyAction="http://tempuri.org/IServiceBiblio/Select_BiblioPrincipaleAdoResponse")]
        System.Threading.Tasks.Task<string> Select_BiblioPrincipaleAdoAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblio/GetAll", ReplyAction="http://tempuri.org/IServiceBiblio/GetAllResponse")]
        BiblioLecteur.ServiceReferenceBiblio.clsBiblio[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblio/GetAll", ReplyAction="http://tempuri.org/IServiceBiblio/GetAllResponse")]
        System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceBiblio.clsBiblio[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBiblioChannel : BiblioLecteur.ServiceReferenceBiblio.IServiceBiblio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBiblioClient : System.ServiceModel.ClientBase<BiblioLecteur.ServiceReferenceBiblio.IServiceBiblio>, BiblioLecteur.ServiceReferenceBiblio.IServiceBiblio {
        
        public ServiceBiblioClient() {
        }
        
        public ServiceBiblioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBiblioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBiblioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBiblioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BiblioLecteur.ServiceReferenceBiblio.clsBiblio[] Select_BiblioPrincipale(string user) {
            return base.Channel.Select_BiblioPrincipale(user);
        }
        
        public System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceBiblio.clsBiblio[]> Select_BiblioPrincipaleAsync(string user) {
            return base.Channel.Select_BiblioPrincipaleAsync(user);
        }
        
        public string Select_BiblioPrincipaleAdo(string user) {
            return base.Channel.Select_BiblioPrincipaleAdo(user);
        }
        
        public System.Threading.Tasks.Task<string> Select_BiblioPrincipaleAdoAsync(string user) {
            return base.Channel.Select_BiblioPrincipaleAdoAsync(user);
        }
        
        public BiblioLecteur.ServiceReferenceBiblio.clsBiblio[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceBiblio.clsBiblio[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
