//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLecteur.ServiceReferenceReservations {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsGeneralReservation", Namespace="http://schemas.datacontract.org/2004/07/wcflibrary")]
    [System.SerializableAttribute()]
    public partial class clsGeneralReservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NbreLivreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string biblioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string livreTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NbreLivre {
            get {
                return this.NbreLivreField;
            }
            set {
                if ((this.NbreLivreField.Equals(value) != true)) {
                    this.NbreLivreField = value;
                    this.RaisePropertyChanged("NbreLivre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string biblio {
            get {
                return this.biblioField;
            }
            set {
                if ((object.ReferenceEquals(this.biblioField, value) != true)) {
                    this.biblioField = value;
                    this.RaisePropertyChanged("biblio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string livreTitle {
            get {
                return this.livreTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.livreTitleField, value) != true)) {
                    this.livreTitleField = value;
                    this.RaisePropertyChanged("livreTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsReservation", Namespace="http://schemas.datacontract.org/2004/07/wcflibrary")]
    [System.SerializableAttribute()]
    public partial class clsReservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string livreTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string livreTitle {
            get {
                return this.livreTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.livreTitleField, value) != true)) {
                    this.livreTitleField = value;
                    this.RaisePropertyChanged("livreTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceReservations.IReservationsService")]
    public interface IReservationsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationsService/getAllUserReservations", ReplyAction="http://tempuri.org/IReservationsService/getAllUserReservationsResponse")]
        BiblioLecteur.ServiceReferenceReservations.clsGeneralReservation[] getAllUserReservations(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationsService/getAllUserReservations", ReplyAction="http://tempuri.org/IReservationsService/getAllUserReservationsResponse")]
        System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceReservations.clsGeneralReservation[]> getAllUserReservationsAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationsService/getAllReservations", ReplyAction="http://tempuri.org/IReservationsService/getAllReservationsResponse")]
        BiblioLecteur.ServiceReferenceReservations.clsReservation[] getAllReservations(string code, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationsService/getAllReservations", ReplyAction="http://tempuri.org/IReservationsService/getAllReservationsResponse")]
        System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceReservations.clsReservation[]> getAllReservationsAsync(string code, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationsService/getReservations", ReplyAction="http://tempuri.org/IReservationsService/getReservationsResponse")]
        System.Data.DataSet getReservations(string biblio, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationsService/getReservations", ReplyAction="http://tempuri.org/IReservationsService/getReservationsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getReservationsAsync(string biblio, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationsService/insertReservation", ReplyAction="http://tempuri.org/IReservationsService/insertReservationResponse")]
        void insertReservation(string nomLivre, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationsService/insertReservation", ReplyAction="http://tempuri.org/IReservationsService/insertReservationResponse")]
        System.Threading.Tasks.Task insertReservationAsync(string nomLivre, string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservationsServiceChannel : BiblioLecteur.ServiceReferenceReservations.IReservationsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationsServiceClient : System.ServiceModel.ClientBase<BiblioLecteur.ServiceReferenceReservations.IReservationsService>, BiblioLecteur.ServiceReferenceReservations.IReservationsService {
        
        public ReservationsServiceClient() {
        }
        
        public ReservationsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BiblioLecteur.ServiceReferenceReservations.clsGeneralReservation[] getAllUserReservations(string userName) {
            return base.Channel.getAllUserReservations(userName);
        }
        
        public System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceReservations.clsGeneralReservation[]> getAllUserReservationsAsync(string userName) {
            return base.Channel.getAllUserReservationsAsync(userName);
        }
        
        public BiblioLecteur.ServiceReferenceReservations.clsReservation[] getAllReservations(string code, string userName) {
            return base.Channel.getAllReservations(code, userName);
        }
        
        public System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceReservations.clsReservation[]> getAllReservationsAsync(string code, string userName) {
            return base.Channel.getAllReservationsAsync(code, userName);
        }
        
        public System.Data.DataSet getReservations(string biblio, string userName) {
            return base.Channel.getReservations(biblio, userName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getReservationsAsync(string biblio, string userName) {
            return base.Channel.getReservationsAsync(biblio, userName);
        }
        
        public void insertReservation(string nomLivre, string userName) {
            base.Channel.insertReservation(nomLivre, userName);
        }
        
        public System.Threading.Tasks.Task insertReservationAsync(string nomLivre, string userName) {
            return base.Channel.insertReservationAsync(nomLivre, userName);
        }
    }
}
