//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLecteur.ServiceReferenceRetard {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsRetardsUsers", Namespace="http://schemas.datacontract.org/2004/07/wcflibrary")]
    [System.SerializableAttribute()]
    public partial class clsRetardsUsers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbrMoisAutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomLecteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime date_empruntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime date_retourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int exemplaireIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal soldeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal tarifEmpruntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal tarifParJourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal tarifRetardField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbrMoisAuto {
            get {
                return this.NbrMoisAutoField;
            }
            set {
                if ((this.NbrMoisAutoField.Equals(value) != true)) {
                    this.NbrMoisAutoField = value;
                    this.RaisePropertyChanged("NbrMoisAuto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomLecteur {
            get {
                return this.NomLecteurField;
            }
            set {
                if ((object.ReferenceEquals(this.NomLecteurField, value) != true)) {
                    this.NomLecteurField = value;
                    this.RaisePropertyChanged("NomLecteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_emprunt {
            get {
                return this.date_empruntField;
            }
            set {
                if ((this.date_empruntField.Equals(value) != true)) {
                    this.date_empruntField = value;
                    this.RaisePropertyChanged("date_emprunt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_retour {
            get {
                return this.date_retourField;
            }
            set {
                if ((this.date_retourField.Equals(value) != true)) {
                    this.date_retourField = value;
                    this.RaisePropertyChanged("date_retour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int exemplaireID {
            get {
                return this.exemplaireIDField;
            }
            set {
                if ((this.exemplaireIDField.Equals(value) != true)) {
                    this.exemplaireIDField = value;
                    this.RaisePropertyChanged("exemplaireID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal solde {
            get {
                return this.soldeField;
            }
            set {
                if ((this.soldeField.Equals(value) != true)) {
                    this.soldeField = value;
                    this.RaisePropertyChanged("solde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal tarifEmprunt {
            get {
                return this.tarifEmpruntField;
            }
            set {
                if ((this.tarifEmpruntField.Equals(value) != true)) {
                    this.tarifEmpruntField = value;
                    this.RaisePropertyChanged("tarifEmprunt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal tarifParJour {
            get {
                return this.tarifParJourField;
            }
            set {
                if ((this.tarifParJourField.Equals(value) != true)) {
                    this.tarifParJourField = value;
                    this.RaisePropertyChanged("tarifParJour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal tarifRetard {
            get {
                return this.tarifRetardField;
            }
            set {
                if ((this.tarifRetardField.Equals(value) != true)) {
                    this.tarifRetardField = value;
                    this.RaisePropertyChanged("tarifRetard");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRetard.IRetards")]
    public interface IRetards {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetards/GetCountRetardsUsersAdo", ReplyAction="http://tempuri.org/IRetards/GetCountRetardsUsersAdoResponse")]
        int GetCountRetardsUsersAdo(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetards/GetCountRetardsUsersAdo", ReplyAction="http://tempuri.org/IRetards/GetCountRetardsUsersAdoResponse")]
        System.Threading.Tasks.Task<int> GetCountRetardsUsersAdoAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetards/GetCountRetardsUsers", ReplyAction="http://tempuri.org/IRetards/GetCountRetardsUsersResponse")]
        void GetCountRetardsUsers(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetards/GetCountRetardsUsers", ReplyAction="http://tempuri.org/IRetards/GetCountRetardsUsersResponse")]
        System.Threading.Tasks.Task GetCountRetardsUsersAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetards/GetAllRetardsUsers", ReplyAction="http://tempuri.org/IRetards/GetAllRetardsUsersResponse")]
        BiblioLecteur.ServiceReferenceRetard.clsRetardsUsers[] GetAllRetardsUsers(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetards/GetAllRetardsUsers", ReplyAction="http://tempuri.org/IRetards/GetAllRetardsUsersResponse")]
        System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceRetard.clsRetardsUsers[]> GetAllRetardsUsersAsync(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRetardsChannel : BiblioLecteur.ServiceReferenceRetard.IRetards, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetardsClient : System.ServiceModel.ClientBase<BiblioLecteur.ServiceReferenceRetard.IRetards>, BiblioLecteur.ServiceReferenceRetard.IRetards {
        
        public RetardsClient() {
        }
        
        public RetardsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetardsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetardsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetardsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetCountRetardsUsersAdo(string userName) {
            return base.Channel.GetCountRetardsUsersAdo(userName);
        }
        
        public System.Threading.Tasks.Task<int> GetCountRetardsUsersAdoAsync(string userName) {
            return base.Channel.GetCountRetardsUsersAdoAsync(userName);
        }
        
        public void GetCountRetardsUsers(string userName) {
            base.Channel.GetCountRetardsUsers(userName);
        }
        
        public System.Threading.Tasks.Task GetCountRetardsUsersAsync(string userName) {
            return base.Channel.GetCountRetardsUsersAsync(userName);
        }
        
        public BiblioLecteur.ServiceReferenceRetard.clsRetardsUsers[] GetAllRetardsUsers(string userName) {
            return base.Channel.GetAllRetardsUsers(userName);
        }
        
        public System.Threading.Tasks.Task<BiblioLecteur.ServiceReferenceRetard.clsRetardsUsers[]> GetAllRetardsUsersAsync(string userName) {
            return base.Channel.GetAllRetardsUsersAsync(userName);
        }
    }
}
